// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.zed;

import org.bytedeco.cuda.cudart.CUctx_st;
import org.bytedeco.cuda.cudart.CUstream_st;
import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.zed.global.zed.*;


/**
\brief Holds the options used to initialize the body tracking module of the \ref Fusion.
 */
@Properties(inherit = us.ihmc.zed.ZEDJavaAPIConfig.class)
public class SL_BodyTrackingFusionParameters extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public SL_BodyTrackingFusionParameters() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public SL_BodyTrackingFusionParameters(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public SL_BodyTrackingFusionParameters(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public SL_BodyTrackingFusionParameters position(long position) {
        return (SL_BodyTrackingFusionParameters)super.position(position);
    }
    @Override public SL_BodyTrackingFusionParameters getPointer(long i) {
        return new SL_BodyTrackingFusionParameters((Pointer)this).offsetAddress(i);
    }

	/**
	* \brief Defines if the object detection will track objects across images flow.
	*
	* Default: true
	*/
	public native @Cast("bool") boolean enable_tracking(); public native SL_BodyTrackingFusionParameters enable_tracking(boolean setter);

	/**
	* \brief Defines if the body fitting will be applied
	*
	* Default: false
	* \note If you enable it and the camera provides data as BODY_18 the fused body format will be BODY_34.
	*/
	public native @Cast("bool") boolean enable_body_fitting(); public native SL_BodyTrackingFusionParameters enable_body_fitting(boolean setter);
}
