// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.zed;

import org.bytedeco.cuda.cudart.CUctx_st;
import org.bytedeco.cuda.cudart.CUstream_st;
import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.zed.global.zed.*;


/**
\brief Structure containing a set of runtime parameters for the object detection module using your own model ran by the SDK.
<p>
The default constructor sets all parameters to their default settings.
\note Parameters can be adjusted by the user.
*/
@Properties(inherit = us.ihmc.zed.ZEDJavaAPIConfig.class)
public class SL_CustomObjectDetectionRuntimeParameters extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public SL_CustomObjectDetectionRuntimeParameters() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public SL_CustomObjectDetectionRuntimeParameters(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public SL_CustomObjectDetectionRuntimeParameters(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public SL_CustomObjectDetectionRuntimeParameters position(long position) {
        return (SL_CustomObjectDetectionRuntimeParameters)super.position(position);
    }
    @Override public SL_CustomObjectDetectionRuntimeParameters getPointer(long i) {
        return new SL_CustomObjectDetectionRuntimeParameters((Pointer)this).offsetAddress(i);
    }

	/**
	\brief Global object detection properties.
	*/
	public native @ByRef SL_CustomObjectDetectionProperties object_detection_properties(); public native SL_CustomObjectDetectionRuntimeParameters object_detection_properties(SL_CustomObjectDetectionProperties setter);

	/**
	\brief Per class object detection properties.
	<p>
	\note \ref object_detection_properties is used as a fallback when SL_CustomObjectDetectionRuntimeParameters.object_class_detection_properties is partially set.
	*/
	public native SL_CustomObjectDetectionProperties object_class_detection_properties(); public native SL_CustomObjectDetectionRuntimeParameters object_class_detection_properties(SL_CustomObjectDetectionProperties setter);

	/**
	\brief Size of the \ref object_class_detection_properties array.
	*/
	public native @Cast("unsigned int") int number_custom_detection_properties(); public native SL_CustomObjectDetectionRuntimeParameters number_custom_detection_properties(int setter);
}
