// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.zed;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.zed.global.zed.*;


/**
\brief Used to identify a specific camera in the Fusion API
 */
@Properties(inherit = us.ihmc.zed.ZEDJavaAPIConfig.class)
public class SL_CameraIdentifier extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public SL_CameraIdentifier() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public SL_CameraIdentifier(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public SL_CameraIdentifier(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public SL_CameraIdentifier position(long position) {
        return (SL_CameraIdentifier)super.position(position);
    }
    @Override public SL_CameraIdentifier getPointer(long i) {
        return new SL_CameraIdentifier((Pointer)this).offsetAddress(i);
    }

	public native @Cast("unsigned long long int") long sn(); public native SL_CameraIdentifier sn(long setter);
}
