// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.zed;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.zed.global.zed.*;


/**
 * \brief Represents a world position in ECEF format.
 *
 */
@Properties(inherit = us.ihmc.zed.ZEDJavaAPIConfig.class)
public class SL_ECEF extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public SL_ECEF() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public SL_ECEF(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public SL_ECEF(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public SL_ECEF position(long position) {
        return (SL_ECEF)super.position(position);
    }
    @Override public SL_ECEF getPointer(long i) {
        return new SL_ECEF((Pointer)this).offsetAddress(i);
    }

	/**
	 * \brief x coordinate of SL_ECEF.
	 *
	 */
	public native double x(); public native SL_ECEF x(double setter);
	/**
	 * \brief y coordinate of SL_ECEF.
	 *
	 */
	public native double y(); public native SL_ECEF y(double setter);
	/**
	 * \brief z coordinate of SL_ECEF.
	 *
	 */
	public native double z(); public native SL_ECEF z(double setter);
}
