// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.zed;

import org.bytedeco.cuda.cudart.CUctx_st;
import org.bytedeco.cuda.cudart.CUstream_st;
import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.zed.global.zed.*;


/**
 * \brief Represents a world position in ENU format.
 *
 */
@Properties(inherit = us.ihmc.zed.ZEDJavaAPIConfig.class)
public class SL_ENU extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public SL_ENU() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public SL_ENU(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public SL_ENU(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public SL_ENU position(long position) {
        return (SL_ENU)super.position(position);
    }
    @Override public SL_ENU getPointer(long i) {
        return new SL_ENU((Pointer)this).offsetAddress(i);
    }

	/**
	 * \brief East coordinate.
	 *
	 */
	public native double east(); public native SL_ENU east(double setter);
	/**
	 * \brief North coordinate.
	 *
	 */
	public native double north(); public native SL_ENU north(double setter);
	/**
	 * \brief Up coordinate.
	 *
	 */
	public native double up(); public native SL_ENU up(double setter);
}
