// Targeted by JavaCPP version 1.5.11: DO NOT EDIT THIS FILE

package us.ihmc.zed;

import org.bytedeco.cuda.cudart.CUctx_st;
import org.bytedeco.cuda.cudart.CUstream_st;
import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.zed.global.zed.*;


/**
\brief Describes one encoded video source exposed by the Camera.
<p>
Returned by \ref sl_get_encoded_streams_info() ??? one entry per source,
whether currently active or not. Use this to discover which sources are
producing data and at what codec/bitrate before calling
\ref sl_retrieve_encoded_stream_packet().
 */
@Properties(inherit = us.ihmc.zed.ZEDJavaAPIConfig.class)
public class SL_EncodedStreamInfo extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public SL_EncodedStreamInfo() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public SL_EncodedStreamInfo(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public SL_EncodedStreamInfo(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public SL_EncodedStreamInfo position(long position) {
        return (SL_EncodedStreamInfo)super.position(position);
    }
    @Override public SL_EncodedStreamInfo getPointer(long i) {
        return new SL_EncodedStreamInfo((Pointer)this).offsetAddress(i);
    }

	public native @Cast("SL_ENCODED_STREAM_SOURCE") int source(); public native SL_EncodedStreamInfo source(int setter);
	/** Non-zero if this source is producing packets right now. */
	public native int active(); public native SL_EncodedStreamInfo active(int setter);
	public native @Cast("SL_STREAMING_CODEC") int codec(); public native SL_EncodedStreamInfo codec(int setter);
	/** Configured bitrate, kbps. 0 for lossless / unknown. */
	public native @Cast("unsigned int") int bitrate_kbps(); public native SL_EncodedStreamInfo bitrate_kbps(int setter);
	/** Non-zero for H264_LOSSLESS / H265_LOSSLESS recording. */
	public native int is_lossless(); public native SL_EncodedStreamInfo is_lossless(int setter);
}
