// Targeted by JavaCPP version 1.5.11: DO NOT EDIT THIS FILE

package us.ihmc.zed;

import org.bytedeco.cuda.cudart.CUctx_st;
import org.bytedeco.cuda.cudart.CUstream_st;
import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.zed.global.zed.*;


/**
\brief Single encoded video packet retrieved from a Camera source.
<p>
Payload is laid out as Annex-B NAL units. The first packet handed back on
a given source is always an IDR, with SPS/PPS (and VPS for HEVC) inlined
in front, so writing successive packets to a {@code .h264} / {@code .hevc} file
produces a stream playable by any standard player.
<p>
\note \ref data is owned by the SDK and remains valid until the next call
to \ref sl_retrieve_encoded_stream_packet() on the same source, or until
the Camera is closed. Other calls do not invalidate the buffer. Copy the
bytes out if you need them longer.
 */
@Properties(inherit = us.ihmc.zed.ZEDJavaAPIConfig.class)
public class SL_EncodedStreamPacket extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public SL_EncodedStreamPacket() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public SL_EncodedStreamPacket(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public SL_EncodedStreamPacket(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public SL_EncodedStreamPacket position(long position) {
        return (SL_EncodedStreamPacket)super.position(position);
    }
    @Override public SL_EncodedStreamPacket getPointer(long i) {
        return new SL_EncodedStreamPacket((Pointer)this).offsetAddress(i);
    }

	/** Annex-B NAL units. SDK-owned. */
	public native @Cast("const unsigned char*") BytePointer data(); public native SL_EncodedStreamPacket data(BytePointer setter);
	/** Length of \ref data in bytes. */
	public native @Cast("uint64_t") long size(); public native SL_EncodedStreamPacket size(long setter);
	/** Capture timestamp (ns). */
	public native @Cast("uint64_t") long timestamp_ns(); public native SL_EncodedStreamPacket timestamp_ns(long setter);
	/** H264 or H265. */
	public native @Cast("SL_STREAMING_CODEC") int codec(); public native SL_EncodedStreamPacket codec(int setter);
	/** Non-zero if this packet is an IDR. */
	public native int is_keyframe(); public native SL_EncodedStreamPacket is_keyframe(int setter);
	/** Which path produced this packet. */
	public native @Cast("SL_ENCODED_STREAM_SOURCE") int source(); public native SL_EncodedStreamPacket source(int setter);
}
