// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.zed;

import org.bytedeco.cuda.cudart.CUctx_st;
import org.bytedeco.cuda.cudart.CUstream_st;
import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.zed.global.zed.*;


/**
* \brief Structure representing a generic 3*3 matrix.
*/
@Properties(inherit = us.ihmc.zed.ZEDJavaAPIConfig.class)
public class SL_Matrix3f extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public SL_Matrix3f() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public SL_Matrix3f(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public SL_Matrix3f(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public SL_Matrix3f position(long position) {
        return (SL_Matrix3f)super.position(position);
    }
    @Override public SL_Matrix3f getPointer(long i) {
        return new SL_Matrix3f((Pointer)this).offsetAddress(i);
    }

	/**
	\brief Array containing the values fo the 3*3 matrix.
	*/
	public native float p(int i); public native SL_Matrix3f p(int i, float setter);
	@MemberGetter public native FloatPointer p();
}
