// Targeted by JavaCPP version 1.5.11: DO NOT EDIT THIS FILE

package us.ihmc.zed;

import org.bytedeco.cuda.cudart.CUctx_st;
import org.bytedeco.cuda.cudart.CUstream_st;
import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.zed.global.zed.*;


/**
\brief Structure containing a set of parameters for the object tracking module.
<p>
The default constructor sets all parameters to their default settings.
\note Parameters can be adjusted by the user.
*/
@Properties(inherit = us.ihmc.zed.ZEDJavaAPIConfig.class)
public class SL_ObjectTrackingParameters extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public SL_ObjectTrackingParameters() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public SL_ObjectTrackingParameters(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public SL_ObjectTrackingParameters(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public SL_ObjectTrackingParameters position(long position) {
        return (SL_ObjectTrackingParameters)super.position(position);
    }
    @Override public SL_ObjectTrackingParameters getPointer(long i) {
        return new SL_ObjectTrackingParameters((Pointer)this).offsetAddress(i);
    }

	/**
	\brief Preset defining the expected maximum acceleration of the tracked object.
	<p>
	Determines how the ZED SDK interprets object acceleration, affecting tracking behavior and predictions.
	 */
	public native @Cast("SL_OBJECT_ACCELERATION_PRESET") int object_acceleration_preset(); public native SL_ObjectTrackingParameters object_acceleration_preset(int setter);

	/**
	\brief Control the smoothing of the velocity estimation.
	Values between 0.0 and 1.0.
	- High value (closer to 1.0): Very smooth, but may lag behind rapid changes.
	- Low value (closer to 0.0): Very responsive to velocity changes, but may be jittery.
	- 0.5: ZED SDK base tuning. Balanced smoothing and responsiveness.
	A negative value (e.g. -1) lets the ZED SDK interpret the velocity_smoothing_factor.
	Default: -1
	*/
	public native float velocity_smoothing_factor(); public native SL_ObjectTrackingParameters velocity_smoothing_factor(float setter);

	/**
	\brief Threshold to force an object's velocity to zero.
	If the calculated speed (m/s) is below this threshold, the object is considered static.
	This helps eliminate drift on stationary objects.
	A negative value (e.g. -1) lets the ZED SDK interpret the min_velocity_threshold.
	Default: -1
	*/
	public native float min_velocity_threshold(); public native SL_ObjectTrackingParameters min_velocity_threshold(float setter);

	/**
	\brief Duration to keep predicting a track's position after occlusion.
	When an object is no longer visible (occluded or out of frame),
	the tracker will predict its position for this duration before deleting the track.
	- Short (e.g., 0.2s): Prevents "ghost" objects but may break tracks during short occlusions.
	- Long (e.g., 2.0s): Maintains ID during long occlusions but may report objects that are gone.
	A negative value (e.g. -1) lets the ZED SDK interpret the prediction_timeout_s.
	Default: -1
	*/
	public native float prediction_timeout_s(); public native SL_ObjectTrackingParameters prediction_timeout_s(float setter);

	/**
	\brief Minimum confirmation time required to validate a track.
	The minimum duration (in seconds) an object must be continuously detected
	before it is reported as a valid track. Helps filter out spurious false
	positives that appear only briefly.
	A negative value (e.g. -1) lets the ZED SDK interpret the min_confirmation_time_s.
	Default: -1
	*/
	public native float min_confirmation_time_s(); public native SL_ObjectTrackingParameters min_confirmation_time_s(float setter);
}
