// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.zed;

import org.bytedeco.cuda.cudart.CUctx_st;
import org.bytedeco.cuda.cudart.CUstream_st;
import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.zed.global.zed.*;


/**
 * \brief Holds the options used for initializing the positional tracking fusion module.
 *
 */
@Properties(inherit = us.ihmc.zed.ZEDJavaAPIConfig.class)
public class SL_PositionalTrackingFusionParameters extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public SL_PositionalTrackingFusionParameters() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public SL_PositionalTrackingFusionParameters(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public SL_PositionalTrackingFusionParameters(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public SL_PositionalTrackingFusionParameters position(long position) {
        return (SL_PositionalTrackingFusionParameters)super.position(position);
    }
    @Override public SL_PositionalTrackingFusionParameters getPointer(long i) {
        return new SL_PositionalTrackingFusionParameters((Pointer)this).offsetAddress(i);
    }

	/**
	 * \brief This attribute is responsible for enabling or not GNSS positional tracking fusion.
	 *
	 * Default: false
	 */
	public native @Cast("bool") boolean enable_GNSS_fusion(); public native SL_PositionalTrackingFusionParameters enable_GNSS_fusion(boolean setter);

	/**
	 * \brief Control the VIO / GNSS calibration process.
	 */
	public native @ByRef SL_GNSSCalibrationParameters gnss_calibration_parameters(); public native SL_PositionalTrackingFusionParameters gnss_calibration_parameters(SL_GNSSCalibrationParameters setter);

	/**
	 * \brief Position of the base footprint with respect to the user world.
	 */
	public native @ByRef SL_Vector3 base_footprint_to_world_translation(); public native SL_PositionalTrackingFusionParameters base_footprint_to_world_translation(SL_Vector3 setter);

	/**
	 * \brief Orientation of the base footprint with respect to the user world.
	 */
	public native @ByRef SL_Quaternion base_footprint_to_world_rotation(); public native SL_PositionalTrackingFusionParameters base_footprint_to_world_rotation(SL_Quaternion setter);

	/**
	 * \brief Position of the base footprint with respect to the baselink
	 */
	public native @ByRef SL_Vector3 base_footprint_to_baselink_translation(); public native SL_PositionalTrackingFusionParameters base_footprint_to_baselink_translation(SL_Vector3 setter);

	/**
	 * \brief Orientation of the base footprint with respect to the baselink
	 */
	public native @ByRef SL_Quaternion base_footprint_to_baselink_rotation(); public native SL_PositionalTrackingFusionParameters base_footprint_to_baselink_rotation(SL_Quaternion setter);

	/**
	 * \brief Whether to override 2 of the 3 rotations from \ref base_footprint_to_world_transform using the IMU gravity.
	 */
	public native @Cast("bool") boolean set_gravity_as_origin(); public native SL_PositionalTrackingFusionParameters set_gravity_as_origin(boolean setter);
	/**
	 * \brief ID of the camera used for positional tracking. If not specified, will use the first camera called with the subscribe() method.
	 *
	 */
	public native @ByRef SL_CameraIdentifier tracking_camera_id(); public native SL_PositionalTrackingFusionParameters tracking_camera_id(SL_CameraIdentifier setter);
}
