// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.zed;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.zed.global.zed.*;


/**
* \brief Structure containing the width and height of an image.
*/
@Properties(inherit = us.ihmc.zed.ZEDJavaAPIConfig.class)
public class SL_Resolution extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public SL_Resolution() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public SL_Resolution(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public SL_Resolution(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public SL_Resolution position(long position) {
        return (SL_Resolution)super.position(position);
    }
    @Override public SL_Resolution getPointer(long i) {
        return new SL_Resolution((Pointer)this).offsetAddress(i);
    }

	/**
	\brief Width of the image in pixels.
	*/
	public native long width(); public native SL_Resolution width(long setter);
	/**
	\brief Height of the image in pixels.
	*/
	public native long height(); public native SL_Resolution height(long setter);
}
