// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.zed;

import org.bytedeco.cuda.cudart.CUctx_st;
import org.bytedeco.cuda.cudart.CUstream_st;
import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.zed.global.zed.*;


/**
\brief Structure representing a transformation (translation and rotation)
*/
@Properties(inherit = us.ihmc.zed.ZEDJavaAPIConfig.class)
public class SL_Transform extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public SL_Transform() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public SL_Transform(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public SL_Transform(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public SL_Transform position(long position) {
        return (SL_Transform)super.position(position);
    }
    @Override public SL_Transform getPointer(long i) {
        return new SL_Transform((Pointer)this).offsetAddress(i);
    }

	/**
	\brief Translation part of the transform.
	*/
	public native @ByRef SL_Vector3 translation(); public native SL_Transform translation(SL_Vector3 setter);
	/**
	\brief Rotation part of the transform.
	*/
	public native @ByRef SL_Quaternion rotation(); public native SL_Transform rotation(SL_Quaternion setter);
}
