// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.zed;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.zed.global.zed.*;


/**
* \brief Structure representing an unsigned char 2-dimensional vector.
*/
@Properties(inherit = us.ihmc.zed.ZEDJavaAPIConfig.class)
public class SL_Uchar2 extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public SL_Uchar2() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public SL_Uchar2(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public SL_Uchar2(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public SL_Uchar2 position(long position) {
        return (SL_Uchar2)super.position(position);
    }
    @Override public SL_Uchar2 getPointer(long i) {
        return new SL_Uchar2((Pointer)this).offsetAddress(i);
    }

	/**
	\brief Fist component of the vector.
	*/
	public native @Cast("unsigned char") byte x(); public native SL_Uchar2 x(byte setter);
	/**
	\brief Second component of the vector.
	*/
	public native @Cast("unsigned char") byte y(); public native SL_Uchar2 y(byte setter);
}
