// Targeted by JavaCPP version 1.5.11: DO NOT EDIT THIS FILE

package us.ihmc.zed;

import org.bytedeco.cuda.cudart.CUctx_st;
import org.bytedeco.cuda.cudart.CUstream_st;
import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.zed.global.zed.*;


/**
\brief Parameters controlling voxel decimation in sl_retrieve_voxel_measure.
 */
@Properties(inherit = us.ihmc.zed.ZEDJavaAPIConfig.class)
public class SL_VoxelMeasureParameters extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public SL_VoxelMeasureParameters() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public SL_VoxelMeasureParameters(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public SL_VoxelMeasureParameters(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public SL_VoxelMeasureParameters position(long position) {
        return (SL_VoxelMeasureParameters)super.position(position);
    }
    @Override public SL_VoxelMeasureParameters getPointer(long i) {
        return new SL_VoxelMeasureParameters((Pointer)this).offsetAddress(i);
    }

	/**
	\brief Voxel grid cell size in coordinate_units defined in SL_InitParameters.
	If <= 0, a 100 mm equivalent default is used. Clamped internally to [5 mm equivalent, max_depth_range].
	 */
	public native float voxel_size(); public native SL_VoxelMeasureParameters voxel_size(float setter);

	/**
	\brief Controls output point positions within each voxel.
	If true, output point positions are the centroid of all points in each voxel.
	If false, output positions are snapped to the voxel grid center.
	 */
	public native @Cast("bool") boolean centroid(); public native SL_VoxelMeasureParameters centroid(boolean setter);

	/**
	\brief How voxel size adapts with depth.
	Default: SL_VOXELIZATION_MODE_STEREO_UNCERTAINTY
	 */
	public native @Cast("SL_VOXELIZATION_MODE") int resolution_mode(); public native SL_VoxelMeasureParameters resolution_mode(int setter);

	/**
	\brief Scale factor for depth-adaptive voxel growth.
	Typical range: [0.01, 1.0]. Clamped internally to [0.01, 3.0].
	\note Only used when resolution_mode is not SL_VOXELIZATION_MODE_FIXED.
	 */
	public native float resolution_scale(); public native SL_VoxelMeasureParameters resolution_scale(float setter);
}
