#name: Run Gradle test
#
#on:
#  push:
#    branches: ["main"]
#  pull_request:
#    branches: ["main"]
#  workflow_dispatch:
#
#jobs:
#  test-linux:
#    runs-on: [ubuntu-20.04]
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-java@v4
#        with:
#          distribution: 'temurin'
#          java-version: '17'
#      - name: Check Java/Gradle versions
#        run: |
#          java --version
#          gradle --version
#      - name: Run tests
#        run: |
#          ./gradlew test
#  test-windows:
#    runs-on: [windows-2019]
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-java@v4
#        with:
#          distribution: 'temurin'
#          java-version: '17'
#      - name: Check Java/Gradle versions
#        run: |
#          java --version
#          gradle --version
#      - name: Run tests
#        run: |
#          ./gradlew test